<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk</name>
   <tag></tag>
   <elementGuidId>0415f3d9-8794-4b9a-bad5-84b6aa6745fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='DialogForm']/div[2]/div[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.login100-form-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Masuk&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e2ec327f-765c-44db-b606-4fc68f179633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login100-form-btn</value>
      <webElementGuid>84aeb582-81b7-4e0a-aea9-eccc7999dc88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Masuk
                        </value>
      <webElementGuid>aa065eb7-cbf4-4a01-8686-9fc7a170708a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DialogForm&quot;)/div[2]/div[@class=&quot;container-login100-form-btn&quot;]/button[@class=&quot;login100-form-btn&quot;]</value>
      <webElementGuid>bdd5a244-4c4f-4e15-b4fc-aa5fbbc071b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='DialogForm']/div[2]/div[3]/button</value>
      <webElementGuid>64c81128-8209-4e15-9864-67adf012e98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk ke Akun Anda'])[1]/following::button[1]</value>
      <webElementGuid>d1df62df-3006-4172-8e2b-fb7ed3d51347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selamat Datang!'])[1]/following::button[1]</value>
      <webElementGuid>259f6c48-154a-48b8-b33f-b71800155072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>31e983a0-396d-40ed-91c7-83feb9a9bb08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>43600ff7-6ba7-49c2-9edc-e689d91e67bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
                            Masuk
                        ' or . = '
                            Masuk
                        ')]</value>
      <webElementGuid>6ee3cdf2-992b-4fc5-b570-ba1e64e6bf64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
