<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2025</name>
   <tag></tag>
   <elementGuidId>b7dce620-6b83-418e-8d5c-d33cedb11e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.datepicker--cell.datepicker--cell-year.-current-.-focus-</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='datepickers-container']/div/div/div/div/div[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;2025&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4e3eb585-2da4-4a0e-8599-ea2e8f751393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker--cell datepicker--cell-year -current- -focus-</value>
      <webElementGuid>82aadbb2-f1ef-448e-a27e-5095f52b0ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-year</name>
      <type>Main</type>
      <value>2025</value>
      <webElementGuid>59cdd065-ec29-4e15-bd65-e8c02df222d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2025</value>
      <webElementGuid>4c236714-b584-4f42-9b01-9e27366d32cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepickers-container&quot;)/div[@class=&quot;datepicker -bottom-left- -from-bottom- active&quot;]/div[@class=&quot;datepicker--content&quot;]/div[@class=&quot;datepicker--years datepicker--body active&quot;]/div[@class=&quot;datepicker--cells datepicker--cells-years&quot;]/div[@class=&quot;datepicker--cell datepicker--cell-year -current- -focus-&quot;]</value>
      <webElementGuid>908eb779-cb33-436a-8272-939ee1e0bb20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datepickers-container']/div/div/div/div/div[7]</value>
      <webElementGuid>2c87b6d2-c03b-4282-88f2-f617aba89f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save changes'])[2]/following::div[16]</value>
      <webElementGuid>d7be9b02-c2fd-4d1f-a6e3-ab303336f6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/following::div[16]</value>
      <webElementGuid>d9b709f2-0246-4f2e-a872-66cc92156cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/preceding::div[6]</value>
      <webElementGuid>32421bab-5a52-496f-a28b-e169ab7cf8cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2025']/parent::*</value>
      <webElementGuid>900a4305-a267-4d66-a416-20b553b19e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[7]</value>
      <webElementGuid>11bf556a-e05b-4a60-9e43-aad56cedc47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '2025' or . = '2025')]</value>
      <webElementGuid>f87b0086-714b-4c5c-8fb5-514661ef753d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
