<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Periode Awal_PeriodeSearchAwal</name>
   <tag></tag>
   <elementGuidId>c4856fde-d1a1-4d10-bc0d-a55fd475b046</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PeriodeSearchAwal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PeriodeSearchAwal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PeriodeSearchAwal</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0dbdf245-8a3d-4ec1-be70-81746a9969c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>60c486d2-a90f-47ab-ab2c-df1dbb840f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PeriodeSearchAwal</value>
      <webElementGuid>8d93dc29-9bee-4640-b95c-1e1d43ca71d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PeriodeSearchAwal</value>
      <webElementGuid>55bdd2cb-963e-46ae-bd46-ffa0ce128918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker-here form-control</value>
      <webElementGuid>0a8ab3d3-d1b8-49df-90b0-eb3f25d55e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bd4ada1c-ee36-498e-af1c-7faf39ca8012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>0e3064a5-a3aa-48f9-817f-a89f61187c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PeriodeSearchAwal&quot;)</value>
      <webElementGuid>5dd68994-aa6a-4202-abb2-6f207d2f4d14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PeriodeSearchAwal']</value>
      <webElementGuid>945385b4-45e5-4b61-9279-adef041c66df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivParameterSearch']/div/div[4]/div/div/div/div/input</value>
      <webElementGuid>77d34b3e-3f54-4593-b73e-ec36ef377c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>bdc019a7-98bd-4933-ad6d-33502a5bca32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'PeriodeSearchAwal' and @name = 'PeriodeSearchAwal']</value>
      <webElementGuid>68296acd-bfb2-4678-a2be-b14dabb25f10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
