<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Periode Akhir_PeriodeSearchAkhir</name>
   <tag></tag>
   <elementGuidId>360f0a69-f8db-4af5-a85f-e45a48e9fc0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PeriodeSearchAkhir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PeriodeSearchAkhir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PeriodeSearchAkhir</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11a4590a-0214-48cc-b8a3-d21c89e2e3e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>648407f4-6419-485d-970e-b3b8560389f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PeriodeSearchAkhir</value>
      <webElementGuid>c3a421f0-0c17-432a-a4d1-1d526d29a15b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PeriodeSearchAkhir</value>
      <webElementGuid>b8da9836-eb20-430d-8591-8997a5a3c39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker-here form-control</value>
      <webElementGuid>4cf1eeef-9a2d-4635-bddf-1efdb7e02152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4896ea5a-8342-4c32-882f-9511000dbe43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>8ac0d444-e31c-425d-91e9-71e745417831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PeriodeSearchAkhir&quot;)</value>
      <webElementGuid>a0898425-04e6-4990-b700-026867e98ec1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PeriodeSearchAkhir']</value>
      <webElementGuid>68b97ae6-733e-4177-bae6-a2dc740d1be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivParameterSearch']/div/div[4]/div/div[2]/div/div/input</value>
      <webElementGuid>38930bfc-2dbe-4f92-9534-b07901c36baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>368db60f-9449-4953-a421-633f2cae8b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'PeriodeSearchAkhir' and @name = 'PeriodeSearchAkhir']</value>
      <webElementGuid>7ebc91d8-62fb-46c8-a6b0-104ea3bdacaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
