<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PeriodeSearchAkhir</name>
   <tag></tag>
   <elementGuidId>9c8f7000-3c9f-403f-b680-401d9f98b3f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PeriodeSearchAkhir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PeriodeSearchAkhir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PeriodeSearchAkhir</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60713812-a7fd-4e15-973f-7b11d5cb8db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a0fb6f0-8a84-4205-9558-aa91fe1bcdd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PeriodeSearchAkhir</value>
      <webElementGuid>4e707e96-f266-4813-8c26-7894b58220b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PeriodeSearchAkhir</value>
      <webElementGuid>1cd2a7f8-9cc1-42b7-a12c-702e586ef501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker-here form-control</value>
      <webElementGuid>06f06683-dca1-4246-be79-c965fc9b623b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ae1c4905-03e3-43ee-b744-8bb2c6347b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PeriodeSearchAkhir&quot;)</value>
      <webElementGuid>6ac541ab-5240-47fc-9a78-169410f2e01d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PeriodeSearchAkhir']</value>
      <webElementGuid>c8a35949-de1e-466d-899c-a6dcdb73154a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>b08b2f86-8166-423e-9705-9da042dd558d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'PeriodeSearchAkhir' and @name = 'PeriodeSearchAkhir']</value>
      <webElementGuid>8569e21a-e3f8-4050-9e0e-8f86dfad6ed2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
