<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_The chart has 1 Y axis displaying valu_2f0e2f</name>
   <tag></tag>
   <elementGuidId>f18d62cd-ca1f-4dc2-9201-20fd2b7df915</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>path.highcharts-point.highcharts-negative.highcharts-point-hover</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@aria-label = 'Januari, Rp -24,356. Total 2025.']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Januari, Rp -24,356. Total 2025.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>babb0543-b475-4baf-b2e0-eb7ee382ee1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>rgb(55,98,217)</value>
      <webElementGuid>52d9061d-9bcb-4b3d-be87-1141959da247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M 33 0 L 46 0 A 0 0 0 0 1 46 0 L 46 22 A 3 3 0 0 1 43 25 L 36 25 A 3 3 0 0 1 33 22 L 33 0 A 0 0 0 0 1 33 0 Z</value>
      <webElementGuid>1f2f91ae-0315-4906-aa26-0bbdefc23cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#ffffff</value>
      <webElementGuid>0a650dbe-c821-4f75-a8f9-521e32cc8c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0eb0b288-9c3b-443c-ad48-37e4859fb426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>opacity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>74ecacf5-4e3c-4d18-b8e0-d4d67935a20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>filter</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>5a9594a4-adae-4749-9099-93d10bf835ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highcharts-point highcharts-negative highcharts-point-hover</value>
      <webElementGuid>278d999c-42fa-4411-a644-293a20c02100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0f6926ea-bd29-4d6b-be4c-e90f1ab6a8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>384fb229-81f8-4a45-a60f-f3cfd1af64bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Januari, Rp -24,356. Total 2025.</value>
      <webElementGuid>6a63f6f2-60e4-4692-961a-956459420875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-8sbjkf0-110&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;highcharts-series-group&quot;]/g[@class=&quot;highcharts-series highcharts-series-6 highcharts-column-series highcharts-tracker highcharts-series-hover&quot;]/path[@class=&quot;highcharts-point highcharts-negative highcharts-point-hover&quot;]</value>
      <webElementGuid>14de00e9-fec3-48ae-ab2a-556745c1433c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
