<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_The chart has 1 Y axis displaying value_TOTAL</name>
   <tag></tag>
   <elementGuidId>00ef848e-863c-4ec7-bbc7-712a6d8ef33e</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>path.highcharts-point.highcharts-negative.highcharts-point-hover</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;highcharts-lrh77e9-0&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;highcharts-series-group&quot;]/g[@class=&quot;highcharts-series highcharts-series-7 highcharts-column-series highcharts-tracker highcharts-series-hover&quot;]/path[@class=&quot;highcharts-point highcharts-point-hover&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Januari, Rp -24,356. Total&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>9533cb61-1df1-4226-9305-eea656de6c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>rgb(55,98,217)</value>
      <webElementGuid>cae35196-2d6c-45ce-8196-f8cac055f851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M 33 0 L 46 0 A 0 0 0 0 1 46 0 L 46 22 A 3 3 0 0 1 43 25 L 36 25 A 3 3 0 0 1 33 22 L 33 0 A 0 0 0 0 1 33 0 Z</value>
      <webElementGuid>44941dd1-5ff8-48bc-8c9c-1bc656a16d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#ffffff</value>
      <webElementGuid>aedb5fed-5f5e-452d-b026-75515a13c9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>35152e19-771a-4b38-9b89-3093b7f53e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>opacity</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e7641292-6d69-44a4-89f4-65b585ebe8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>filter</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>d3ddf8fa-b963-442b-a1fe-9669cdb3bd29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highcharts-point highcharts-negative highcharts-point-hover</value>
      <webElementGuid>7d134ea0-c13d-49f4-8faf-f7cf6b1ece0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8a97f94e-04af-471f-b743-798714cc0e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ba6349d9-d5c9-454a-889e-b802cafc4978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Januari, Rp -24,356. Total 2025.</value>
      <webElementGuid>976db95a-4029-4e60-9637-3cd5e841367c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-xbnp7jq-0&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;highcharts-series-group&quot;]/g[@class=&quot;highcharts-series highcharts-series-6 highcharts-column-series highcharts-tracker highcharts-series-hover&quot;]/path[@class=&quot;highcharts-point highcharts-negative highcharts-point-hover&quot;]</value>
      <webElementGuid>9e52ea36-a468-4abc-940e-740dd0c12339</webElementGuid>
   </webElementProperties>
</WebElementEntity>
