<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-Silakan pilih-_1_2_4</name>
   <tag></tag>
   <elementGuidId>52ffc8df-b611-42bd-ad1a-f603ba68fb3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-jenisParameter-container > span.select2-selection__placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-jenisParameter-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-jenisParameter-container >> internal:text=&quot;-Silakan pilih-&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>584bebe2-f38c-4a41-8b2e-9fd826f1eaa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__placeholder</value>
      <webElementGuid>fb7a94eb-a521-479b-b9d9-a07df72c07a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Silakan pilih-</value>
      <webElementGuid>8e64b830-e172-4ff4-82f5-7731cafd17af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-jenisParameter-container&quot;)/span[@class=&quot;select2-selection__placeholder&quot;]</value>
      <webElementGuid>524bf16e-ff13-4d63-8849-3253849318c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-jenisParameter-container']/span</value>
      <webElementGuid>845b06d8-7903-4914-a9c4-29f32c8de2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::span[5]</value>
      <webElementGuid>a58f33de-fc01-42a2-8aad-bda15d004c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/span/span/span/span</value>
      <webElementGuid>52e3fe4f-e168-4400-a3fc-4c7e563c11fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '-Silakan pilih-' or . = '-Silakan pilih-')]</value>
      <webElementGuid>96e6f16b-9235-4c9d-b178-9d5f4d93eddf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
