<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_9015294067 - ASANA WIRASTA SETIA</name>
   <tag></tag>
   <elementGuidId>2c3a90c4-8cb3-4865-9204-577a11e62330</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-DebiturExistingId-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-DebiturExistingId-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;×9015294067 - ASANA WIRASTA SETIA&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c3de9fca-bf48-46b5-9db3-49fa3c3cdc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>e152d98b-3fbe-49a7-8d85-d640634d24cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-DebiturExistingId-container</value>
      <webElementGuid>4c967411-9a84-4859-a2de-4a0498872d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>9015294067 - ASANA WIRASTA SETIA</value>
      <webElementGuid>aab68b32-39b4-444c-82e8-c70c171212b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×9015294067 - ASANA WIRASTA SETIA</value>
      <webElementGuid>060466ff-c162-4902-8f5a-95b1bb7477eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-DebiturExistingId-container&quot;)</value>
      <webElementGuid>78abf36e-84de-4861-8ffd-66a67932c1fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-DebiturExistingId-container']</value>
      <webElementGuid>2ba317eb-77a1-4d01-9377-eb8c1f9e3c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divGroup']/div/div/span/span/span/span</value>
      <webElementGuid>9aec3fbf-99e9-43a4-bb1c-cbe62b86b55b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[4]</value>
      <webElementGuid>c06b047a-9abf-4f61-b824-5dcd2f36b836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>1d49c6d1-59cb-4a3e-937d-90a72faf65c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-DebiturExistingId-container' and @title = '9015294067 - ASANA WIRASTA SETIA' and (text() = '×9015294067 - ASANA WIRASTA SETIA' or . = '×9015294067 - ASANA WIRASTA SETIA')]</value>
      <webElementGuid>c49083c4-fa31-4cd0-b82d-ddb895ed742c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
