<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-Silakan pilih-_1_2</name>
   <tag></tag>
   <elementGuidId>87fb65ce-09cb-4eca-a777-dd4412a94656</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-jenisParameter-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-jenisParameter-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-jenisParameter-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>866beef5-854b-4e31-8746-7d7d76519918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>194d3b12-8968-44b7-a4dc-0939d0be0992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-jenisParameter-container</value>
      <webElementGuid>d22bebba-d49a-4f02-93ac-663b8cb4b1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Silakan pilih-</value>
      <webElementGuid>2db624d8-3bf2-439a-8464-b16749ff6aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-jenisParameter-container&quot;)</value>
      <webElementGuid>7920e10f-a1c9-45d6-b815-9f28fef523bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-jenisParameter-container']</value>
      <webElementGuid>92d70a83-7042-4dab-8d14-4865b97ec9d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::span[4]</value>
      <webElementGuid>342e2640-f8b5-45d2-a105-52377e53d03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/span/span/span</value>
      <webElementGuid>ba6bd68a-ccb7-4bbe-9e8e-bb27e59a0270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-jenisParameter-container' and (text() = '-Silakan pilih-' or . = '-Silakan pilih-')]</value>
      <webElementGuid>3f0d8505-5f31-4697-b587-250e78630475</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
