<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-Silakan pilih-_1_2_3</name>
   <tag></tag>
   <elementGuidId>1df025f4-6168-4f87-82e2-a93afd2064ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-JenisEntitas-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-JenisEntitas-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-JenisEntitas-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9b2b5860-3146-4e2a-b25b-aee06f599e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>0c4ddb3b-108e-41cd-b073-5f3a1badb2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-JenisEntitas-container</value>
      <webElementGuid>4f65e22f-9e90-4e0f-ab47-743aa166ed31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Silakan pilih-</value>
      <webElementGuid>8a2b603d-0cf7-4350-a288-bc39c06c10a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-JenisEntitas-container&quot;)</value>
      <webElementGuid>65f2fa48-1e8e-4a11-9fc6-0c0df5e1ca04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-JenisEntitas-container']</value>
      <webElementGuid>cac736dd-db6c-40eb-9612-abff2b859f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='divGroup']/div/div/span/span/span/span)[5]</value>
      <webElementGuid>315e8a2d-d1b9-4759-ad3f-39c2d1bfa5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::span[4]</value>
      <webElementGuid>d02f96d3-4b1c-4f0b-9984-40f86e47c26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari Data'])[1]/preceding::span[4]</value>
      <webElementGuid>8411c77b-7022-401c-a0a6-60e5ee35c672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/span/span/span/span</value>
      <webElementGuid>fc613332-b521-439a-bde1-458b7b8b59a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-JenisEntitas-container' and (text() = '-Silakan pilih-' or . = '-Silakan pilih-')]</value>
      <webElementGuid>4d23aa1e-801c-480e-b899-5fc668b1f493</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
