<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2025</name>
   <tag></tag>
   <elementGuidId>887f99df-6b92-4c42-9ce9-35d5bd0e65f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='datepickers-container']/div/div/div/div/div[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.datepicker--cell.datepicker--cell-year.-current-.-focus-</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;2025&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4794c084-b55d-446a-bc6a-8999e9363911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker--cell datepicker--cell-year -current- -focus-</value>
      <webElementGuid>1d7e47fa-3023-4f91-9700-5fd32f69c524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-year</name>
      <type>Main</type>
      <value>2025</value>
      <webElementGuid>24ce51c8-93ae-40a1-b87c-786951cb1a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2025</value>
      <webElementGuid>b5013e6c-8507-42e1-9995-e215c42d99ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepickers-container&quot;)/div[@class=&quot;datepicker -bottom-left- -from-bottom- active&quot;]/div[@class=&quot;datepicker--content&quot;]/div[@class=&quot;datepicker--years datepicker--body active&quot;]/div[@class=&quot;datepicker--cells datepicker--cells-years&quot;]/div[@class=&quot;datepicker--cell datepicker--cell-year -current- -focus-&quot;]</value>
      <webElementGuid>e839d9e4-a858-4b8f-ae23-277b21b60ef3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datepickers-container']/div/div/div/div/div[7]</value>
      <webElementGuid>02c40666-4351-4687-8611-27ebb42b216a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save changes'])[2]/following::div[16]</value>
      <webElementGuid>954193b2-9089-41f3-bd04-800182321cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/following::div[16]</value>
      <webElementGuid>e4715539-0487-4a1d-ad84-4c6cb19d4def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Очистить'])[1]/preceding::div[6]</value>
      <webElementGuid>b776fe4e-c3e1-4409-ad02-cdd0a703d086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2025']/parent::*</value>
      <webElementGuid>8f763850-79d0-443d-891a-bb357b7a9e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[7]</value>
      <webElementGuid>c636f075-a9ce-4c4f-88b2-6fcdac008e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '2025' or . = '2025')]</value>
      <webElementGuid>fef0f9e5-20c5-4524-84dc-ec832763423e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
