<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PeriodeSearchAkhir</name>
   <tag></tag>
   <elementGuidId>4d804197-b52f-4959-91e9-8e75823216da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PeriodeSearchAkhir']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PeriodeSearchAkhir</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#PeriodeSearchAkhir</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee9ac11c-322f-45e8-bd86-c91d3e61bd59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95b564ca-a6f1-4f48-b59e-5b514bf4341b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PeriodeSearchAkhir</value>
      <webElementGuid>834abd8f-5ba2-41de-872f-d00d2b3dd44d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PeriodeSearchAkhir</value>
      <webElementGuid>7649c088-5a21-489a-85d1-8d1c0df22cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker-here form-control</value>
      <webElementGuid>233f5c94-4920-4afd-9c39-9a1e4460eb9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dd652d6a-0d4a-4c0c-b1fb-b0d0cffc7881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PeriodeSearchAkhir&quot;)</value>
      <webElementGuid>aa5639ac-25db-43cd-9ed7-a61d8820bf04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PeriodeSearchAkhir']</value>
      <webElementGuid>617e5d0e-5f9d-4e43-b554-ee670e012917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>0aa00933-ad5f-4058-ad60-bfb0232f1205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'PeriodeSearchAkhir' and @name = 'PeriodeSearchAkhir']</value>
      <webElementGuid>7510941b-dde3-41a3-95ed-3e7a61cdf239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
