<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-Silakan pilih-_1_2_3</name>
   <tag></tag>
   <elementGuidId>9c214e8f-a996-4aa5-95fe-60e40da6139f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-JenisEntitas-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-JenisEntitas-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-JenisEntitas-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ba184913-4776-48fd-abf4-a3bb5edd4734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>33b29633-44bf-4492-90a5-51f128818668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-JenisEntitas-container</value>
      <webElementGuid>e5324601-2cf0-40a2-8f7d-35fec784dfca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Silakan pilih-</value>
      <webElementGuid>28e5bac3-cb5e-41ed-8ea7-6f26abfbe467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-JenisEntitas-container&quot;)</value>
      <webElementGuid>e90d1576-20fd-4fa8-88e8-adbceaceb112</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-JenisEntitas-container']</value>
      <webElementGuid>7bc5cb05-8444-4cab-9e43-e5b231cec3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='divGroup']/div/div/span/span/span/span)[5]</value>
      <webElementGuid>d1650d4b-b269-4fad-861e-787da515ee8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::span[4]</value>
      <webElementGuid>a6f91227-ffa0-40b3-b586-98f4a911521c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari Data'])[1]/preceding::span[4]</value>
      <webElementGuid>8bf37ce7-d07d-4453-9c9f-f63ef461dcef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/span/span/span/span</value>
      <webElementGuid>aabb41b4-fd3f-4b53-921c-548725ac3258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-JenisEntitas-container' and (text() = '-Silakan pilih-' or . = '-Silakan pilih-')]</value>
      <webElementGuid>42732f6a-7923-4bd0-959c-d7c88ea8146e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
