<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-Silakan pilih-_1</name>
   <tag></tag>
   <elementGuidId>2dabe737-535f-4966-bea1-b0bad0468578</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-JenisReport-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-JenisReport-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-JenisReport-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>054de9ca-e2ed-4e88-9622-a003990a94b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>1f72acbc-56da-4338-9454-06013691bdab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-JenisReport-container</value>
      <webElementGuid>e98278c6-6abb-4f9d-b010-29bb4fadab78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-Silakan pilih-</value>
      <webElementGuid>e9491551-7cab-4133-bff8-9fee791c3ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-JenisReport-container&quot;)</value>
      <webElementGuid>9b26a891-ddb3-450f-8f23-9535fecc26da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-JenisReport-container']</value>
      <webElementGuid>9ab98a06-b8e5-49ed-a15a-b899f04ae70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='divGroup']/div/div/span/span/span/span)[3]</value>
      <webElementGuid>2e756fe7-b8a2-41eb-b255-509ce33dbd45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[4]</value>
      <webElementGuid>9342c982-db9f-4702-be99-4b75cf62ed58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span/span/span/span</value>
      <webElementGuid>edf4151e-41ba-4e8b-b000-d8ca6fca3e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-JenisReport-container' and (text() = '-Silakan pilih-' or . = '-Silakan pilih-')]</value>
      <webElementGuid>d6af2f67-3970-4cbb-9743-6b8daa0aa817</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
