<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_9014551301 - VANADIUM M E</name>
   <tag></tag>
   <elementGuidId>f3473025-6ac3-41ee-854d-ad7c3abdaa73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-DebiturExistingId-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-DebiturExistingId-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;×9014551301 - VANADIUM M E&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>31d4f093-2b89-4396-99e4-963c0d6ee989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>f06e3d27-1fc5-4347-a7a8-3ec059b75155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-DebiturExistingId-container</value>
      <webElementGuid>d10c813d-fc99-4f73-bcf4-21fec38468af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>9014551301 - VANADIUM M E</value>
      <webElementGuid>f3db9559-8f42-4f8a-aeea-04fd322d009a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×9014551301 - VANADIUM M E</value>
      <webElementGuid>33b3ddc1-f2e0-452e-ac64-b545ef50fd36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-DebiturExistingId-container&quot;)</value>
      <webElementGuid>ab31f459-3ab7-40fe-80d0-4423e74c4dbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-DebiturExistingId-container']</value>
      <webElementGuid>175d4e53-193e-4625-aaa8-fb440275c2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divGroup']/div/div/span/span/span/span</value>
      <webElementGuid>755f71e4-97d9-44d4-837b-88f093c41163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[4]</value>
      <webElementGuid>35d1d499-646c-442a-be74-1b6f2c230493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>56676427-49df-4fb4-8248-af3b640bedb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-DebiturExistingId-container' and @title = '9014551301 - VANADIUM M E' and (text() = '×9014551301 - VANADIUM M E' or . = '×9014551301 - VANADIUM M E')]</value>
      <webElementGuid>977a5509-ad25-43ca-83a8-d7a8f53c7d4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
